"""
Conversation Memory — Seven AI

Treats conversations as first-class memory objects (episodes), not just
strings of turns. Each conversation has a start, an end, participants,
a summary, extracted action items, sentiment, and dominant mood.

Inspired by the conversation-memory pattern used in AI wearables like
omi — adapted for Seven's offline-first, local-only philosophy. All data
lives in the same ~/.chatbot/memory.db used by the rest of Seven.

Two tables:
  conversations  — one row per conversation episode
  utterances     — one row per spoken/typed line, linked to a conversation

Sources:
  'direct'   — the user talking to Seven (from bot's main input loop)
  'ambient'  — passive audio captured in the background
  'imported' — transcripts brought in from elsewhere

Usage:
    from core.conversation_memory import ConversationMemory

    cm = ConversationMemory()
    cid = cm.start_conversation(source='direct', participants=['user'])
    cm.add_utterance(cid, speaker='user', text='hello seven')
    cm.add_utterance(cid, speaker='seven', text='hi Jan, how can I help?')
    cm.finalize_conversation(cid, ollama=bot.ollama)
    recent = cm.get_recent(limit=5)
"""

import json
import logging
import sqlite3
import threading
from datetime import datetime, timedelta
from pathlib import Path
from typing import Any, Dict, List, Optional

import config

logger = logging.getLogger("ConversationMemory")


SCHEMA_VERSION = 1


# ============================================================================
# Schema
# ============================================================================

CREATE_CONVERSATIONS_SQL = """
CREATE TABLE IF NOT EXISTS conversations (
    id               INTEGER PRIMARY KEY AUTOINCREMENT,
    session_id       TEXT,
    started_at       DATETIME NOT NULL,
    ended_at         DATETIME,
    source           TEXT NOT NULL DEFAULT 'direct',
    participants     TEXT NOT NULL DEFAULT '[]',
    location         TEXT,
    summary          TEXT,
    topics           TEXT NOT NULL DEFAULT '[]',
    action_items     TEXT NOT NULL DEFAULT '[]',
    sentiment        TEXT,
    mood             TEXT,
    utterance_count  INTEGER NOT NULL DEFAULT 0,
    word_count       INTEGER NOT NULL DEFAULT 0,
    finalized        INTEGER NOT NULL DEFAULT 0,
    created_at       DATETIME DEFAULT CURRENT_TIMESTAMP
);
"""

CREATE_UTTERANCES_SQL = """
CREATE TABLE IF NOT EXISTS utterances (
    id               INTEGER PRIMARY KEY AUTOINCREMENT,
    conversation_id  INTEGER NOT NULL,
    timestamp        DATETIME NOT NULL,
    speaker          TEXT NOT NULL DEFAULT 'unknown',
    text             TEXT NOT NULL,
    source           TEXT NOT NULL DEFAULT 'direct',
    confidence       REAL,
    emotion          TEXT,
    created_at       DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (conversation_id) REFERENCES conversations(id) ON DELETE CASCADE
);
"""

CREATE_INDEXES_SQL = [
    "CREATE INDEX IF NOT EXISTS idx_conv_started ON conversations(started_at);",
    "CREATE INDEX IF NOT EXISTS idx_conv_source  ON conversations(source);",
    "CREATE INDEX IF NOT EXISTS idx_conv_final   ON conversations(finalized);",
    "CREATE INDEX IF NOT EXISTS idx_utt_conv     ON utterances(conversation_id);",
    "CREATE INDEX IF NOT EXISTS idx_utt_ts       ON utterances(timestamp);",
    "CREATE INDEX IF NOT EXISTS idx_utt_speaker  ON utterances(speaker);",
]


# ============================================================================
# ConversationMemory
# ============================================================================

class ConversationMemory:
    """
    Episode-level memory for Seven. Each conversation is one episode,
    made up of utterances (individual lines). Summaries, action items,
    topics, and sentiment are generated by Ollama on finalize.

    Thread-safe: uses a lock around all writes.
    """

    def __init__(self, db_path: Optional[Path] = None):
        self.db_path: Path = Path(db_path) if db_path else Path(config.DB_PATH)
        self._lock = threading.RLock()
        self._init_schema()
        logger.info(f"[CONVMEM] Initialized — db={self.db_path}")

    # -------------------- Internals --------------------

    def _conn(self) -> sqlite3.Connection:
        conn = sqlite3.connect(self.db_path, timeout=15.0)
        conn.row_factory = sqlite3.Row
        conn.execute("PRAGMA foreign_keys = ON;")
        return conn

    def _init_schema(self):
        with self._lock:
            conn = self._conn()
            try:
                cur = conn.cursor()
                cur.execute(CREATE_CONVERSATIONS_SQL)
                cur.execute(CREATE_UTTERANCES_SQL)
                for idx in CREATE_INDEXES_SQL:
                    cur.execute(idx)
                conn.commit()
            except Exception as e:
                logger.error(f"[CONVMEM] Schema init failed: {e}")
            finally:
                conn.close()

    @staticmethod
    def _row_to_conv(row: sqlite3.Row) -> Dict[str, Any]:
        d = dict(row)
        for f in ("participants", "topics", "action_items"):
            try:
                d[f] = json.loads(d.get(f) or "[]")
            except Exception:
                d[f] = []
        return d

    # -------------------- Conversation lifecycle --------------------

    def start_conversation(
        self,
        source: str = "direct",
        participants: Optional[List[str]] = None,
        location: Optional[str] = None,
        session_id: Optional[str] = None,
    ) -> int:
        """Open a new conversation. Returns its id."""
        participants = participants or ["user"]
        now = datetime.now().isoformat()
        with self._lock:
            conn = self._conn()
            try:
                cur = conn.cursor()
                cur.execute(
                    """
                    INSERT INTO conversations
                        (session_id, started_at, source, participants, location)
                    VALUES (?, ?, ?, ?, ?)
                    """,
                    (session_id, now, source, json.dumps(participants), location),
                )
                conn.commit()
                conv_id = cur.lastrowid
                logger.debug(f"[CONVMEM] Started conv #{conv_id} ({source})")
                return conv_id
            finally:
                conn.close()

    def add_utterance(
        self,
        conversation_id: int,
        speaker: str,
        text: str,
        source: str = "direct",
        confidence: Optional[float] = None,
        emotion: Optional[str] = None,
        timestamp: Optional[datetime] = None,
    ) -> int:
        """Append an utterance to a conversation."""
        text = (text or "").strip()
        if not text:
            return 0
        ts = (timestamp or datetime.now()).isoformat()
        word_count = len(text.split())
        with self._lock:
            conn = self._conn()
            try:
                cur = conn.cursor()
                cur.execute(
                    """
                    INSERT INTO utterances
                        (conversation_id, timestamp, speaker, text, source, confidence, emotion)
                    VALUES (?, ?, ?, ?, ?, ?, ?)
                    """,
                    (conversation_id, ts, speaker, text, source, confidence, emotion),
                )
                cur.execute(
                    """
                    UPDATE conversations
                       SET utterance_count = utterance_count + 1,
                           word_count      = word_count + ?
                     WHERE id = ?
                    """,
                    (word_count, conversation_id),
                )
                conn.commit()
                return cur.lastrowid
            except Exception as e:
                logger.debug(f"[CONVMEM] add_utterance failed: {e}")
                return 0
            finally:
                conn.close()

    def end_conversation(self, conversation_id: int) -> bool:
        """Mark a conversation as closed (no summary yet)."""
        now = datetime.now().isoformat()
        with self._lock:
            conn = self._conn()
            try:
                cur = conn.cursor()
                cur.execute(
                    "UPDATE conversations SET ended_at = ? WHERE id = ? AND ended_at IS NULL",
                    (now, conversation_id),
                )
                conn.commit()
                return cur.rowcount > 0
            finally:
                conn.close()

    def finalize_conversation(
        self,
        conversation_id: int,
        ollama: Any = None,
        model: Optional[str] = None,
    ) -> Dict[str, Any]:
        """
        Close the conversation (if open), generate summary/action items/sentiment
        via Ollama when available, and stamp the row as finalized.

        Args:
            conversation_id: the conversation to finalize.
            ollama:          object with `.generate(prompt, system_message=..., temperature=..., max_tokens=...)`
                             matching the pattern used elsewhere in Seven.
            model:           optional model name override.

        Returns:
            dict with the finalized conversation row.
        """
        # Make sure it's closed
        self.end_conversation(conversation_id)

        transcript_lines = self._get_transcript_lines(conversation_id)
        if not transcript_lines:
            # empty conversation — just mark finalized and move on
            with self._lock:
                conn = self._conn()
                try:
                    conn.execute(
                        "UPDATE conversations SET finalized = 1 WHERE id = ?",
                        (conversation_id,),
                    )
                    conn.commit()
                finally:
                    conn.close()
            return self.get_conversation(conversation_id) or {}

        transcript = "\n".join(transcript_lines)

        summary, topics, action_items, sentiment, mood = self._generate_summary(
            transcript, ollama=ollama, model=model
        )

        with self._lock:
            conn = self._conn()
            try:
                conn.execute(
                    """
                    UPDATE conversations
                       SET summary      = ?,
                           topics       = ?,
                           action_items = ?,
                           sentiment    = ?,
                           mood         = ?,
                           finalized    = 1
                     WHERE id = ?
                    """,
                    (
                        summary,
                        json.dumps(topics),
                        json.dumps(action_items),
                        sentiment,
                        mood,
                        conversation_id,
                    ),
                )
                conn.commit()
            finally:
                conn.close()

        logger.info(
            f"[CONVMEM] Finalized conv #{conversation_id} — "
            f"{len(transcript_lines)} utterances, "
            f"{len(action_items)} action items, sentiment={sentiment}"
        )
        return self.get_conversation(conversation_id) or {}

    def _get_transcript_lines(self, conversation_id: int) -> List[str]:
        conn = self._conn()
        try:
            cur = conn.cursor()
            cur.execute(
                """
                SELECT speaker, text FROM utterances
                 WHERE conversation_id = ?
                 ORDER BY timestamp ASC, id ASC
                """,
                (conversation_id,),
            )
            return [f"{r['speaker']}: {r['text']}" for r in cur.fetchall()]
        finally:
            conn.close()

    # -------------------- LLM-backed summarization --------------------

    def _generate_summary(
        self,
        transcript: str,
        ollama: Any = None,
        model: Optional[str] = None,
    ) -> tuple:
        """
        Ask Ollama to produce a JSON summary. Falls back to a lightweight
        heuristic summary when Ollama is unavailable or fails.

        Returns: (summary, topics, action_items, sentiment, mood)
        """
        # Trim transcript so we don't blow through the context window
        snippet = transcript if len(transcript) < 8000 else transcript[-8000:]

        if ollama is not None:
            prompt = (
                "Below is a conversation transcript. Respond with ONLY a valid JSON "
                "object (no prose, no markdown fences) with these exact keys:\n"
                '  "summary"      : 2-4 sentence plain-language summary\n'
                '  "topics"       : list of 1-5 short topic strings\n'
                '  "action_items" : list of concrete TODOs mentioned (can be empty)\n'
                '  "sentiment"    : one of "positive", "negative", "neutral", "mixed"\n'
                '  "mood"         : the dominant mood of the speaker in one word\n'
                "\nTranscript:\n"
                f"{snippet}\n"
            )
            try:
                kwargs: Dict[str, Any] = dict(
                    system_message=(
                        "You are a precise summarizer. You return valid JSON only, "
                        "never prose or markdown."
                    ),
                    temperature=0.2,
                    max_tokens=400,
                )
                if model:
                    kwargs["model"] = model
                raw = ollama.generate(prompt, **kwargs)
                if raw:
                    parsed = self._parse_summary_json(raw)
                    if parsed:
                        return parsed
            except Exception as e:
                logger.debug(f"[CONVMEM] Ollama summary failed: {e}")

        # Heuristic fallback
        return self._heuristic_summary(transcript)

    @staticmethod
    def _parse_summary_json(raw: str) -> Optional[tuple]:
        """Defensively extract the JSON object even if the model wraps it in fences."""
        try:
            s = (raw or "").strip()
            # Strip markdown fences
            if s.startswith("```"):
                s = s.strip("`")
                if s.lower().startswith("json"):
                    s = s[4:]
                s = s.strip()
            # Pull out the first {...} block
            start = s.find("{")
            end = s.rfind("}")
            if start != -1 and end != -1 and end > start:
                s = s[start : end + 1]
            obj = json.loads(s)
            summary = str(obj.get("summary", "")).strip()
            if not summary:
                return None
            topics = obj.get("topics") or []
            if not isinstance(topics, list):
                topics = [str(topics)]
            topics = [str(t).strip() for t in topics if str(t).strip()][:5]
            action_items = obj.get("action_items") or []
            if not isinstance(action_items, list):
                action_items = [str(action_items)]
            action_items = [str(a).strip() for a in action_items if str(a).strip()]
            sentiment = str(obj.get("sentiment", "neutral")).strip().lower() or "neutral"
            if sentiment not in {"positive", "negative", "neutral", "mixed"}:
                sentiment = "neutral"
            mood = str(obj.get("mood", "")).strip().lower() or None
            return summary, topics, action_items, sentiment, mood
        except Exception:
            return None

    @staticmethod
    def _heuristic_summary(transcript: str) -> tuple:
        """When Ollama isn't there, produce a minimal summary so the row isn't empty."""
        lines = [ln for ln in transcript.splitlines() if ln.strip()]
        first = lines[0] if lines else ""
        last = lines[-1] if lines else ""
        summary = (
            f"{len(lines)}-line exchange. Opens: {first[:120]}. "
            f"Closes: {last[:120]}."
        )
        return summary, [], [], "neutral", None

    # -------------------- Queries --------------------

    def get_conversation(self, conversation_id: int) -> Optional[Dict[str, Any]]:
        conn = self._conn()
        try:
            cur = conn.cursor()
            cur.execute("SELECT * FROM conversations WHERE id = ?", (conversation_id,))
            row = cur.fetchone()
            return self._row_to_conv(row) if row else None
        finally:
            conn.close()

    def get_utterances(self, conversation_id: int) -> List[Dict[str, Any]]:
        conn = self._conn()
        try:
            cur = conn.cursor()
            cur.execute(
                """
                SELECT * FROM utterances
                 WHERE conversation_id = ?
                 ORDER BY timestamp ASC, id ASC
                """,
                (conversation_id,),
            )
            return [dict(r) for r in cur.fetchall()]
        finally:
            conn.close()

    def get_recent(
        self,
        limit: int = 10,
        source: Optional[str] = None,
        finalized_only: bool = False,
    ) -> List[Dict[str, Any]]:
        sql = "SELECT * FROM conversations"
        clauses, params = [], []
        if source:
            clauses.append("source = ?")
            params.append(source)
        if finalized_only:
            clauses.append("finalized = 1")
        if clauses:
            sql += " WHERE " + " AND ".join(clauses)
        sql += " ORDER BY started_at DESC LIMIT ?"
        params.append(limit)

        conn = self._conn()
        try:
            cur = conn.cursor()
            cur.execute(sql, params)
            return [self._row_to_conv(r) for r in cur.fetchall()]
        finally:
            conn.close()

    def get_by_date(self, date_str: str) -> List[Dict[str, Any]]:
        """date_str in YYYY-MM-DD format."""
        conn = self._conn()
        try:
            cur = conn.cursor()
            cur.execute(
                """
                SELECT * FROM conversations
                 WHERE DATE(started_at) = DATE(?)
                 ORDER BY started_at ASC
                """,
                (date_str,),
            )
            return [self._row_to_conv(r) for r in cur.fetchall()]
        finally:
            conn.close()

    def get_today(self) -> List[Dict[str, Any]]:
        return self.get_by_date(datetime.now().strftime("%Y-%m-%d"))

    def get_yesterday(self) -> List[Dict[str, Any]]:
        y = (datetime.now() - timedelta(days=1)).strftime("%Y-%m-%d")
        return self.get_by_date(y)

    def search(self, query: str, limit: int = 20) -> List[Dict[str, Any]]:
        """Naive case-insensitive LIKE search over summary and utterance text."""
        q = f"%{query.lower()}%"
        conn = self._conn()
        try:
            cur = conn.cursor()
            cur.execute(
                """
                SELECT DISTINCT c.* FROM conversations c
                LEFT JOIN utterances u ON u.conversation_id = c.id
                 WHERE LOWER(COALESCE(c.summary, '')) LIKE ?
                    OR LOWER(COALESCE(u.text, ''))    LIKE ?
                 ORDER BY c.started_at DESC
                 LIMIT ?
                """,
                (q, q, limit),
            )
            return [self._row_to_conv(r) for r in cur.fetchall()]
        finally:
            conn.close()

    def get_action_items(self, days_back: int = 7) -> List[Dict[str, Any]]:
        """Collect all action items from conversations in the last N days."""
        since = (datetime.now() - timedelta(days=days_back)).isoformat()
        conn = self._conn()
        try:
            cur = conn.cursor()
            cur.execute(
                """
                SELECT id, started_at, action_items FROM conversations
                 WHERE started_at >= ? AND action_items IS NOT NULL AND action_items != '[]'
                 ORDER BY started_at DESC
                """,
                (since,),
            )
            out = []
            for r in cur.fetchall():
                try:
                    items = json.loads(r["action_items"] or "[]")
                except Exception:
                    items = []
                for it in items:
                    out.append(
                        {
                            "conversation_id": r["id"],
                            "started_at": r["started_at"],
                            "item": it,
                        }
                    )
            return out
        finally:
            conn.close()

    def get_stats(self) -> Dict[str, Any]:
        conn = self._conn()
        try:
            cur = conn.cursor()
            cur.execute("SELECT COUNT(*) AS c FROM conversations")
            total = cur.fetchone()["c"]
            cur.execute("SELECT COUNT(*) AS c FROM conversations WHERE finalized = 1")
            finalized = cur.fetchone()["c"]
            cur.execute("SELECT COUNT(*) AS c FROM utterances")
            utterances = cur.fetchone()["c"]
            cur.execute(
                """
                SELECT source, COUNT(*) AS c FROM conversations GROUP BY source
                """
            )
            by_source = {r["source"]: r["c"] for r in cur.fetchall()}
            cur.execute(
                """
                SELECT COUNT(*) AS c FROM conversations
                 WHERE DATE(started_at) = DATE('now','localtime')
                """
            )
            today = cur.fetchone()["c"]
            return {
                "total_conversations": total,
                "finalized_conversations": finalized,
                "total_utterances": utterances,
                "by_source": by_source,
                "today": today,
            }
        finally:
            conn.close()

    # -------------------- Maintenance --------------------

    def prune_older_than(self, days: int) -> int:
        """Delete conversations (and their utterances via FK cascade) older than N days."""
        cutoff = (datetime.now() - timedelta(days=days)).isoformat()
        with self._lock:
            conn = self._conn()
            try:
                cur = conn.cursor()
                cur.execute(
                    "DELETE FROM conversations WHERE started_at < ?",
                    (cutoff,),
                )
                deleted = cur.rowcount
                conn.commit()
                if deleted:
                    logger.info(f"[CONVMEM] Pruned {deleted} conversation(s) older than {days}d")
                return deleted
            finally:
                conn.close()

    def close_stale(self, minutes: int = 60) -> List[int]:
        """
        Close any conversation whose last utterance was more than N minutes ago.
        Returns list of conversation ids that were closed. Does NOT finalize
        (no summary yet) — the ambient listener handles that separately.
        """
        cutoff = (datetime.now() - timedelta(minutes=minutes)).isoformat()
        with self._lock:
            conn = self._conn()
            try:
                cur = conn.cursor()
                cur.execute(
                    """
                    SELECT c.id FROM conversations c
                     WHERE c.ended_at IS NULL
                       AND COALESCE(
                             (SELECT MAX(u.timestamp) FROM utterances u
                               WHERE u.conversation_id = c.id),
                             c.started_at
                           ) < ?
                    """,
                    (cutoff,),
                )
                ids = [r["id"] for r in cur.fetchall()]
                for cid in ids:
                    cur.execute(
                        "UPDATE conversations SET ended_at = CURRENT_TIMESTAMP WHERE id = ?",
                        (cid,),
                    )
                conn.commit()
                return ids
            finally:
                conn.close()
